### ISSUE TITLE
How to visual the trained model on cityflow?

### ISSUE THREAD

**Issue by CYBruce** [wingsweihua/presslight#2]
Should I use the reply.py to visualize the multi-intersection signal control task in the cityflow simulator?

**Comment by wingsweihua** [comment]
For visualizing the results, you need to set the "SAVEREPLAY" to True in runexp.py, then you can follow the instructions here (https://cityflow.readthedocs.io/en/latest/replay.html) to replay the running files in "self.path_to_log".
